### PR TITLE
Feature/version flag

### PR DESCRIPTION
**Pull request by charlieallatson**
Adds a version flag to the CLI, called with '-v' or '--version'
Created a new _version.py file which will store the version and is imported into both cli.py and setup.py.

### CODE REVIEW

**Comment by dmytrostriletskyi** [comment]
@charlieallatson, hey, thanks for pull request. But can we store a version within `__init__` file instead of creating separate one?

**Comment by charlieallatson** [comment]
@dmytrostriletskyi sure I just didn't like importing things form __init__, how would you suggest to organise the imports?

**Comment by charlieallatson** [comment]
@dmytrostriletskyi  Never mind  - fixed now

**Comment by dmytrostriletskyi** [comment]
@charlieallatson, hey, cool work. I will test the code, then merge. Thanks you! :)

**Pull request merged**
